services:
  - type: web
    name: limpa-nome-expresso
    env: static
    buildCommand: npm install && npm run build
    publishPath: dist
    autoDeploy: yes
    branch: main
    repo: https://github.com/foratoleo/limpa-nome-expresso-site
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
