import { FormSection } from '@/types/form';

export const PETICAO_INICIAL_FORM_SCHEMA: FormSection[] = [
  {
    id: 'dados_pessoais',
    title: 'Dados Pessoais',
    description: 'Informações pessoais do autor da ação',
    isExpanded: true,
    fields: [
      {
        id: 'nome_completo_maiusculas',
        label: 'Nome Completo (em maiúsculas)',
        type: 'text',
        placeholder: '[PREENCHER: SEU NOME COMPLETO EM MAIÚSCULAS]',
        required: true,
        section: 'dados_pessoais',
        preFillFrom: 'name',
        maxLength: 100,
      },
      {
        id: 'estado_civil',
        label: 'Estado Civil',
        type: 'text',
        placeholder: '[PREENCHER: estado civil — ex: solteiro(a)]',
        required: true,
        section: 'dados_pessoais',
        maxLength: 50,
      },
      {
        id: 'profissao',
        label: 'Profissão',
        type: 'text',
        placeholder: '[PREENCHER: profissão — ex: autônomo(a)]',
        required: true,
        section: 'dados_pessoais',
        maxLength: 100,
      },
      {
        id: 'rg',
        label: 'RG',
        type: 'text',
        placeholder: '[PREENCHER: número do RG]',
        required: true,
        section: 'dados_pessoais',
        maxLength: 20,
        validation: {
          pattern: /^\d{1,3}(\.\d{3})?-?\d?$/,
          errorMessage: 'RG inválido. Use o formato: 12.345.678-9 ou 12345678-9',
        },
      },
      {
        id: 'cpf',
        label: 'CPF',
        type: 'text',
        placeholder: '[PREENCHER: 000.000.000-00]',
        required: true,
        section: 'dados_pessoais',
        preFillFrom: 'cpf',
        maxLength: 14,
        validation: {
          pattern: /^\d{3}\.\d{3}\.\d{3}-\d{2}$/,
          errorMessage: 'CPF inválido. Use o formato: 000.000.000-00',
        },
      },
    ],
  },
  {
    id: 'endereco_contato',
    title: 'Endereço e Contato',
    description: 'Informações de residência e contato',
    fields: [
      {
        id: 'endereco_completo',
        label: 'Endereço Completo',
        type: 'text',
        placeholder: '[PREENCHER: endereço completo com CEP]',
        required: true,
        section: 'endereco_contato',
        maxLength: 200,
      },
      {
        id: 'telefone',
        label: 'Telefone',
        type: 'text',
        placeholder: '[PREENCHER: (11) 9xxxx-xxxx]',
        required: true,
        section: 'endereco_contato',
        preFillFrom: 'phone',
        maxLength: 20,
        validation: {
          pattern: /^\(\d{2}\)\s?\d{4,5}-\d{4}$/,
          errorMessage: 'Telefone inválido. Use o formato: (11) 91234-5678',
        },
      },
      {
        id: 'email',
        label: 'E-mail',
        type: 'text',
        placeholder: '[PREENCHER: seu@email.com]',
        required: true,
        section: 'endereco_contato',
        preFillFrom: 'email',
        maxLength: 100,
        validation: {
          pattern: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
          errorMessage: 'E-mail inválido',
        },
      },
    ],
  },
  {
    id: 'comarca',
    title: 'Comarca (Cidade)',
    description: 'Informação sobre o local do processo',
    fields: [
      {
        id: 'cidade_bairro',
        label: 'Cidade/Bairro em SP',
        type: 'text',
        placeholder: '[PREENCHER: nome da sua cidade/bairro em SP]',
        required: true,
        section: 'comarca',
        maxLength: 100,
      },
    ],
  },
  {
    id: 'empresa_requerida',
    title: 'Empresa Requerida',
    description: 'Dados da empresa que negativou',
    fields: [
      {
        id: 'nome_empresa',
        label: 'Nome Completo da Empresa',
        type: 'text',
        placeholder: '[PREENCHER: NOME COMPLETO DA EMPRESA QUE NEGATIVOU — ex: CLARO S.A.]',
        required: true,
        section: 'empresa_requerida',
        maxLength: 200,
      },
      {
        id: 'cnpj_empresa',
        label: 'CNPJ da Empresa',
        type: 'text',
        placeholder: '[PREENCHER: 00.000.000/0001-00]',
        required: true,
        section: 'empresa_requerida',
        maxLength: 18,
        validation: {
          pattern: /^\d{2}\.\d{3}\.\d{3}\/\d{4}-\d{2}$/,
          errorMessage: 'CNPJ inválido. Use o formato: 00.000.000/0001-00',
        },
      },
      {
        id: 'endereco_empresa',
        label: 'Endereço da Empresa',
        type: 'text',
        placeholder: '[PREENCHER: endereço da empresa]',
        required: true,
        section: 'empresa_requerida',
        maxLength: 200,
      },
    ],
  },
  {
    id: 'debito',
    title: 'Dados do Débito',
    description: 'Informações sobre a dívida',
    fields: [
      {
        id: 'valor_debito',
        label: 'Valor do Débito',
        type: 'currency',
        placeholder: '[PREENCHER: valor do débito]',
        required: true,
        section: 'debito',
      },
      {
        id: 'data_vencimento',
        label: 'Data de Vencimento',
        type: 'date',
        placeholder: '[PREENCHER: data de vencimento]',
        required: true,
        section: 'debito',
      },
    ],
  },
  {
    id: 'negativa',
    title: 'Dados da Negativação',
    description: 'Informações sobre quando e como ocorreu a negativação',
    fields: [
      {
        id: 'data_negativa',
        label: 'Data da Negativação',
        type: 'date',
        placeholder: '[PREENCHER: data da negativa — ex: 15/02/2026]',
        required: true,
        section: 'negativa',
      },
      {
        id: 'numero_anexo',
        label: 'Número do Anexo Comprobatório',
        type: 'text',
        placeholder: '[PREENCHER: número do anexo]',
        required: true,
        section: 'negativa',
        maxLength: 50,
      },
      {
        id: 'prejuizo',
        label: 'Descrição do Prejuízo',
        type: 'textarea',
        placeholder: '[PREENCHER: descreva o prejuízo — ex: realizar um financiamento imobiliário junto ao Banco Itaú / obter um cartão de crédito / assinar um contrato de trabalho que exigia nome limpo]',
        required: true,
        section: 'negativa',
        maxLength: 500,
      },
    ],
  },
  {
    id: 'valores_acao',
    title: 'Valores da Ação',
    description: 'Valores para pedidos de indenização',
    fields: [
      {
        id: 'valor_danos_morais',
        label: 'Valor dos Danos Morais',
        type: 'currency',
        placeholder: '[PREENCHER: sugestão entre R$ 3.000 e R$ 5.000]',
        required: true,
        section: 'valores_acao',
      },
      {
        id: 'valor_causa',
        label: 'Valor da Causa',
        type: 'currency',
        placeholder: '[PREENCHER: soma do valor do débito + valor dos danos morais — ex: R$ 8.500,00]',
        required: true,
        section: 'valores_acao',
      },
    ],
  },
  {
    id: 'data_assinatura',
    title: 'Data de Assinatura',
    description: 'Data para assinatura da petição',
    fields: [
      {
        id: 'dia_assinatura',
        label: 'Dia',
        type: 'number',
        placeholder: '[PREENCHER: dia]',
        required: true,
        section: 'data_assinatura',
        validation: {
          pattern: /^(1?[1-9]|[12][0-9]|3[01])$/,
          errorMessage: 'Dia inválido. Deve ser entre 1 e 31',
        },
      },
      {
        id: 'mes_assinatura',
        label: 'Mês',
        type: 'text',
        placeholder: '[PREENCHER: mês]',
        required: true,
        section: 'data_assinatura',
        maxLength: 20,
      },
      {
        id: 'nome_completo_assinatura',
        label: 'Nome Completo para Assinatura',
        type: 'text',
        placeholder: '[PREENCHER: SEU NOME COMPLETO]',
        required: true,
        section: 'data_assinatura',
        preFillFrom: 'name',
        maxLength: 100,
      },
      {
        id: 'cpf_assinatura',
        label: 'CPF para Assinatura',
        type: 'text',
        placeholder: '[PREENCHER: 000.000.000-00]',
        required: true,
        section: 'data_assinatura',
        preFillFrom: 'cpf',
        maxLength: 14,
        validation: {
          pattern: /^\d{3}\.\d{3}\.\d{3}-\d{2}$/,
          errorMessage: 'CPF inválido. Use o formato: 000.000.000-00',
        },
      },
    ],
  },
];
